.\" Manpage for Noizebox.
.\" go to  https://github.com/lhondareyte/noizebox to correct errors or typos.
.TH MAN 8 "1 March 2016" "1.0" "noizebox man page"
.SH NAME
noizebox \- Fluidsynth based sound synthesizer
.SH SYNOPSIS
noizebox [/dev/midi...]
.SH DESCRIPTION
Noizebox is a Fluidsynth based synthesizer. It is designed for midi-windcontrolers, with embbeded platform in mind.
.SH OPTIONS
You can specify any midi device from command line. One thread will be create by available device.
.SH SEE ALSO
fluidsynth(8), snd(4)
.SH BUGS
Probably many.
.SH AUTHOR
Luc Hondareyte 
